require: rubocop

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 16

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ParameterLists:
  Max: 10

RSpec/ExampleLength:
  Max: 25

Metrics/BlockLength:
  ExcludedMethods: ['describe']

Metrics/AbcSize:
  Max: 30

RSpec/MessageSpies:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enable: false

Naming/HeredocDelimiterNaming:
  Enable: false
