---
:authors:
- &10 !ruby/object:Author
  name: Merlyn Daugherty
  biography: Recusandae doloremque ut veritatis et qui. Quam et repellat in vel cumque
    pariatur repellendus et. Assumenda enim sunt quos magni saepe consequatur aut.
- &18 !ruby/object:Author
  name: Janeth Hand
  biography: Expedita et blanditiis mollitia nihil aut dolores. Omnis molestiae consequatur
    dolorem nostrum. Molestiae et placeat dicta labore.
- &6 !ruby/object:Author
  name: Maddie Boehm
  biography: Mollitia ut accusantium ut voluptas. Maiores quisquam facilis expedita
    vero. Praesentium dignissimos quos officiis repellat sunt culpa. Dolor modi asperiores
    id nobis voluptatum atque.
- !ruby/object:Author
  name: Dorla Friesen
  biography: Sunt voluptatem quisquam odio aut. Perspiciatis similique odit sed aut
    tenetur. Fugit non culpa et dolores sed. Consequatur molestiae delectus deserunt
    dolores inventore ratione rerum.
- &4 !ruby/object:Author
  name: Pamella Wuckert
  biography: Explicabo voluptas eius possimus sint quas. Sit provident unde eos quis
    eius atque fuga. Magni est error architecto eos. Quaerat porro sunt aut commodi.
    Qui commodi necessitatibus sed dolorem.
- !ruby/object:Author
  name: Bonny Leannon
  biography: Reprehenderit sequi qui magni ut eum dolores. Sed non tenetur necessitatibus
    ut officiis sit qui pariatur. Accusantium non est optio assumenda exercitationem
    cum atque.
- &3 !ruby/object:Author
  name: Rex Bogisich
  biography: Voluptas numquam rerum recusandae deleniti. Dolore est tempore et facilis
    labore. Blanditiis laboriosam aut et ut inventore. Beatae provident sint ut enim.
    Sed commodi perferendis accusantium id et.
- !ruby/object:Author
  name: Kristopher Dickinson
  biography: Culpa et libero est in ut ex qui ipsam. Aliquid qui nobis necessitatibus
    tempore et eaque dicta. Sed consequatur est explicabo praesentium asperiores voluptatem
    neque veniam. Qui deleniti fuga ut doloribus quas eligendi. Itaque dolorem ut
    recusandae hic.
- &7 !ruby/object:Author
  name: Cherelle Huel
  biography: Laborum consectetur animi tempora tempore eum. Unde animi aliquid delectus
    est consequuntur. Iste quas nam impedit labore dolor.
- !ruby/object:Author
  name: Jennell Hansen
  biography: Est eaque aspernatur similique voluptatum id nobis distinctio corporis.
    Velit error aut rerum sed. Provident et magnam qui et ipsam inventore repudiandae
    et.
- &15 !ruby/object:Author
  name: Alta Batz
  biography: Qui assumenda nam quibusdam sit doloribus neque rerum perferendis. Non
    similique tempora facere quis quos nihil. Omnis autem natus voluptas modi sed
    quia ipsam excepturi. Corrupti nihil odit nulla ad aut dolores non.
- &1 !ruby/object:Author
  name: Loreta Bogisich
  biography: Voluptatem esse quia aut provident quidem vel. Modi maiores et suscipit
    vitae dicta id. Optio laudantium voluptatem sed quibusdam quasi nihil eos iure.
    Quos rerum voluptatem quisquam maxime et.
- &2 !ruby/object:Author
  name: Lane Schmitt
  biography: Et veniam consequatur dicta eos sunt. Enim et error nobis dicta corporis
    assumenda qui. Quas quidem eaque voluptatum est iste. Placeat a rerum qui libero.
- &5 !ruby/object:Author
  name: Alina Schultz
  biography: Culpa odit et voluptas dolore eaque. Asperiores non at debitis veritatis.
    Quis similique a temporibus atque numquam quisquam.
- &17 !ruby/object:Author
  name: Elmira Torp
  biography: Saepe consequatur dolores quasi rerum. Pariatur perferendis error et
    vitae. Enim perspiciatis voluptas consectetur nemo deleniti quia necessitatibus
    officiis.
- !ruby/object:Author
  name: Leonora Pfannerstill
  biography: Assumenda pariatur dolorum saepe omnis similique dolorem et reprehenderit.
    Maiores et et quidem et omnis. Dolorem nemo veniam qui mollitia quaerat aliquid
    nihil quibusdam. Sunt occaecati consectetur et repellat cumque saepe sit.
- &13 !ruby/object:Author
  name: Wally Larkin
  biography: Repudiandae quas temporibus accusantium eveniet neque mollitia rerum.
    Facere nam autem non labore aperiam laborum sequi. Debitis consequatur voluptatem
    rem in est.
- &9 !ruby/object:Author
  name: Howard Treutel
  biography: Aliquam repellat voluptas modi velit et at rerum voluptatibus. Vel itaque
    quam consequatur ex et non doloribus eos. Dicta vel nihil fugiat quidem rem maxime.
- &12 !ruby/object:Author
  name: Nicholas Heller
  biography: Hic nihil qui ea sunt distinctio quo delectus ut. Commodi dolorum voluptatem
    id incidunt esse a enim aliquid. Quia ut quibusdam sed pariatur. Ut ipsam repudiandae
    velit quo et nam.
- !ruby/object:Author
  name: Geoffrey Rath
  biography: Sit et et et dicta pariatur hic reiciendis inventore. Et a et eaque eligendi.
    Quia ut enim sunt mollitia eos ratione veritatis. Impedit dolorem ea harum dolor
    saepe nobis.
- &16 !ruby/object:Author
  name: Russ VonRueden
  biography: Animi doloremque sed libero facere minima. Voluptatum quia alias inventore
    aspernatur est sed cupiditate excepturi. Officiis dolorem dolore commodi facilis
    ut. Doloribus id et minima voluptas enim ut.
- !ruby/object:Author
  name: Jarrod Funk
  biography: Sequi aliquid eos dolores adipisci. Soluta nemo vel consequatur laudantium
    optio. Fugit placeat ullam consequatur iste numquam. Ut nihil et debitis molestiae
    nulla et perspiciatis.
- &14 !ruby/object:Author
  name: Mikaela Breitenberg
  biography: Ipsa reiciendis et est maxime consequatur animi nostrum cupiditate. Omnis
    qui accusantium itaque consectetur non sed alias. Vel soluta expedita sunt voluptatem.
- &8 !ruby/object:Author
  name: Jonathan Parker
  biography: Eos dolorem aliquid nihil similique. Debitis porro est voluptatem mollitia
    saepe architecto reprehenderit. Incidunt dolor et velit voluptas vitae culpa.
- &11 !ruby/object:Author
  name: Daysi Hackett
  biography: Veritatis adipisci architecto ipsa et. Sit fugit ut dolor in nam. Corporis
    eveniet deserunt inventore debitis ea quos laudantium. Explicabo odit quis qui
    consectetur.
:books:
- !ruby/object:Book
  title: American Fly
  author: *1
- &51 !ruby/object:Book
  title: Day of the Nuclear Wolves
  author: *2
- &36 !ruby/object:Book
  title: Invasion of the Killer Rain
  author: *3
- &27 !ruby/object:Book
  title: I am Red World
  author: *4
- &57 !ruby/object:Book
  title: American Brains
  author: *5
- &49 !ruby/object:Book
  title: Action Wolves
  author: *6
- &50 !ruby/object:Book
  title: A Fistful of Red Cousins
  author: *7
- &25 !ruby/object:Book
  title: Season of the Danger Beast
  author: *8
- &48 !ruby/object:Book
  title: Forbidden Man
  author: *9
- &44 !ruby/object:Book
  title: Forbidden Ninja
  author: *10
- &45 !ruby/object:Book
  title: Flying Woman
  author: *7
- &60 !ruby/object:Book
  title: Invasion of the American Witch
  author: *11
- &33 !ruby/object:Book
  title: Time of the Fake Woman
  author: *2
- &19 !ruby/object:Book
  title: Rise of the Fake Women
  author: *12
- &54 !ruby/object:Book
  title: A Fistful of Ultra Pickpocket
  author: *13
- &40 !ruby/object:Book
  title: 'Codename: Flying Wizard'
  author: *14
- !ruby/object:Book
  title: Death Brain
  author: *15
- &43 !ruby/object:Book
  title: Journey of the Red Pickpocket
  author: *16
- &21 !ruby/object:Book
  title: Invasion of the Forbidden Friday
  author: *17
- &29 !ruby/object:Book
  title: Fake Jungle
  author: *12
- &31 !ruby/object:Book
  title: Electric Diaries
  author: *1
- &38 !ruby/object:Book
  title: The Tokyo Identity
  author: *11
- !ruby/object:Book
  title: Fake Diaries
  author: *3
- &61 !ruby/object:Book
  title: Flying Tentacle
  author: *18
- &23 !ruby/object:Book
  title: Tokyo Men
  author: *7
:readers:
- &58 !ruby/object:Reader
  name: Alva Littel
  email: lesha@rippinjenkins.us
  city: Creminchester
  street: Javier Shore
  house: 2657
- !ruby/object:Reader
  name: Myles O'Connell
  email: sumiko@schaden.name
  city: Lake Ayesha
  street: Minh Burg
  house: 870
- &22 !ruby/object:Reader
  name: Odis Zemlak
  email: hee@denesik.name
  city: Mikkiburgh
  street: Thora Mission
  house: 1515
- &42 !ruby/object:Reader
  name: Tyisha Hartmann
  email: jutta_wilkinson@sauerchristiansen.ca
  city: Lake Romanabury
  street: Halvorson Route
  house: 7819
- &46 !ruby/object:Reader
  name: Steffanie Lubowitz
  email: shandi@okeefe.co.uk
  city: Brittanieberg
  street: Jakubowski Burg
  house: 6091
- &35 !ruby/object:Reader
  name: Augusta Breitenberg
  email: raelene@konopelski.biz
  city: Cummerataside
  street: Krajcik Club
  house: 350
- &62 !ruby/object:Reader
  name: Jefferson Walker
  email: shemeka.quigley@creminnicolas.info
  city: Port Serena
  street: Gibson Fort
  house: 62685
- &32 !ruby/object:Reader
  name: Sherwood Russel
  email: ozell@mcclure.co.uk
  city: New Demetriusfort
  street: Micah Fort
  house: 35935
- !ruby/object:Reader
  name: Tana Kuvalis
  email: kristyn_boehm@homenick.info
  city: Port Madonna
  street: Welch Mill
  house: 67177
- &59 !ruby/object:Reader
  name: Stephani VonRueden
  email: leo@stracke.ca
  city: Littlemouth
  street: Erna Trail
  house: 64
- &30 !ruby/object:Reader
  name: Ellis Rohan
  email: milford@barton.com
  city: South Tameka
  street: Charlesetta Lakes
  house: 319
- &47 !ruby/object:Reader
  name: Darnell Gulgowski
  email: marcelle_padberg@kohler.ca
  city: Salomeburgh
  street: Bogan Heights
  house: 81208
- &34 !ruby/object:Reader
  name: Ailene Lehner
  email: mariano_ortiz@hilpert.co.uk
  city: New Elke
  street: Geraldo Fords
  house: 521
- !ruby/object:Reader
  name: Pearlene Ebert
  email: dione@kilback.ca
  city: North Shemeka
  street: Naida Vista
  house: 570
- &37 !ruby/object:Reader
  name: Anja Satterfield
  email: ross_gleichner@thiel.info
  city: Feestport
  street: Andre Manors
  house: 3629
- &41 !ruby/object:Reader
  name: Brett Morissette
  email: carlyn_abshire@koepp.biz
  city: Satterfieldtown
  street: Bess Ville
  house: 65665
- &20 !ruby/object:Reader
  name: Buck Sporer
  email: reyna@barrows.biz
  city: Lake Chris
  street: Gretchen Throughway
  house: 23505
- &39 !ruby/object:Reader
  name: Walter Denesik
  email: darrel.gibson@turnerlesch.co.uk
  city: Macejkovictown
  street: Gleichner Keys
  house: 964
- &52 !ruby/object:Reader
  name: Quyen Armstrong
  email: casimira.bruen@turcottekilback.ca
  city: Quigleyberg
  street: Athena Pass
  house: 26430
- &55 !ruby/object:Reader
  name: Carmella Runolfsdottir
  email: tran.pagac@ratkemosciski.name
  city: New Felton
  street: Marisela Place
  house: 58805
- &26 !ruby/object:Reader
  name: Venita Beier
  email: reiko@schmelerdibbert.co.uk
  city: South Daniel
  street: Lesch Fort
  house: 4790
- &24 !ruby/object:Reader
  name: Cherlyn O'Keefe
  email: forrest@abernathy.ca
  city: Veolabury
  street: Raymon Mission
  house: 49848
- &28 !ruby/object:Reader
  name: Mark Batz
  email: calvin@nitzsche.name
  city: Lake Juan
  street: Rowe Route
  house: 2501
- &56 !ruby/object:Reader
  name: Mi Feeney
  email: felecia@collins.co.uk
  city: West Marcenetown
  street: Boyer Trail
  house: 2941
- &53 !ruby/object:Reader
  name: Jewell Bashirian
  email: margarete.mckenzie@schaefermetz.info
  city: North Pastyland
  street: Kemberly Cape
  house: 7464
:orders:
- !ruby/object:Order
  book: *19
  reader: *20
  date: 2019-07-23
- !ruby/object:Order
  book: *21
  reader: *22
  date: 2019-07-23
- !ruby/object:Order
  book: *23
  reader: *24
  date: 2019-07-23
- !ruby/object:Order
  book: *25
  reader: *26
  date: 2019-07-23
- !ruby/object:Order
  book: *27
  reader: *28
  date: 2019-07-23
- !ruby/object:Order
  book: *29
  reader: *30
  date: 2019-07-23
- !ruby/object:Order
  book: *31
  reader: *32
  date: 2019-07-23
- !ruby/object:Order
  book: *33
  reader: *34
  date: 2019-07-23
- !ruby/object:Order
  book: *33
  reader: *35
  date: 2019-07-23
- !ruby/object:Order
  book: *36
  reader: *35
  date: 2019-07-23
- !ruby/object:Order
  book: *27
  reader: *35
  date: 2019-07-23
- !ruby/object:Order
  book: *27
  reader: *37
  date: 2019-07-23
- !ruby/object:Order
  book: *21
  reader: *26
  date: 2019-07-23
- !ruby/object:Order
  book: *38
  reader: *39
  date: 2019-07-23
- !ruby/object:Order
  book: *40
  reader: *41
  date: 2019-07-23
- !ruby/object:Order
  book: *25
  reader: *30
  date: 2019-07-23
- !ruby/object:Order
  book: *25
  reader: *41
  date: 2019-07-23
- !ruby/object:Order
  book: *19
  reader: *42
  date: 2019-07-23
- !ruby/object:Order
  book: *21
  reader: *26
  date: 2019-07-23
- !ruby/object:Order
  book: *43
  reader: *37
  date: 2019-07-23
- !ruby/object:Order
  book: *44
  reader: *34
  date: 2019-07-23
- !ruby/object:Order
  book: *45
  reader: *46
  date: 2019-07-23
- !ruby/object:Order
  book: *19
  reader: *47
  date: 2019-07-23
- !ruby/object:Order
  book: *48
  reader: *24
  date: 2019-07-23
- !ruby/object:Order
  book: *49
  reader: *39
  date: 2019-07-23
- !ruby/object:Order
  book: *23
  reader: *41
  date: 2019-07-23
- !ruby/object:Order
  book: *50
  reader: *39
  date: 2019-07-23
- !ruby/object:Order
  book: *51
  reader: *42
  date: 2019-07-23
- !ruby/object:Order
  book: *49
  reader: *52
  date: 2019-07-23
- !ruby/object:Order
  book: *29
  reader: *53
  date: 2019-07-23
- !ruby/object:Order
  book: *19
  reader: *26
  date: 2019-07-23
- !ruby/object:Order
  book: *40
  reader: *30
  date: 2019-07-23
- !ruby/object:Order
  book: *54
  reader: *22
  date: 2019-07-23
- !ruby/object:Order
  book: *27
  reader: *32
  date: 2019-07-23
- !ruby/object:Order
  book: *31
  reader: *55
  date: 2019-07-23
- !ruby/object:Order
  book: *29
  reader: *56
  date: 2019-07-23
- !ruby/object:Order
  book: *27
  reader: *55
  date: 2019-07-23
- !ruby/object:Order
  book: *21
  reader: *56
  date: 2019-07-23
- !ruby/object:Order
  book: *23
  reader: *55
  date: 2019-07-23
- !ruby/object:Order
  book: *57
  reader: *46
  date: 2019-07-23
- !ruby/object:Order
  book: *44
  reader: *58
  date: 2019-07-23
- !ruby/object:Order
  book: *36
  reader: *58
  date: 2019-07-23
- !ruby/object:Order
  book: *44
  reader: *37
  date: 2019-07-23
- !ruby/object:Order
  book: *57
  reader: *59
  date: 2019-07-23
- !ruby/object:Order
  book: *40
  reader: *46
  date: 2019-07-23
- !ruby/object:Order
  book: *19
  reader: *32
  date: 2019-07-23
- !ruby/object:Order
  book: *60
  reader: *59
  date: 2019-07-23
- !ruby/object:Order
  book: *29
  reader: *22
  date: 2019-07-23
- !ruby/object:Order
  book: *61
  reader: *53
  date: 2019-07-23
- !ruby/object:Order
  book: *23
  reader: *62
  date: 2019-07-23
