---
:authors:
- &14 !ruby/object:Author
  name: Samantha Morar
  biography: Ut ut sunt ducimus id aspernatur. Deserunt sed cumque quaerat maiores.
    Eveniet aspernatur doloremque velit delectus illum rerum.
- &3 !ruby/object:Author
  name: Pasquale Okuneva
  biography: Voluptates quia eius sunt minus rerum. Libero odio illum doloribus ratione
    saepe enim inventore expedita. Placeat amet quibusdam non qui saepe.
- !ruby/object:Author
  name: Arcelia Dare
  biography: Iusto magni illo perferendis consequatur ea quo tempora at. Quaerat omnis
    accusamus laboriosam ut. Magni aut illo aperiam ut molestiae vero quod. Consectetur
    veritatis quo ab cupiditate ducimus ut.
- &15 !ruby/object:Author
  name: Ilda Brekke
  biography: Tempora tempore ut rerum unde est. Ipsum ab velit esse laboriosam impedit.
    Fugiat labore est doloribus dignissimos.
- &5 !ruby/object:Author
  name: Belia Witting
  biography: Voluptatem vitae officiis voluptate tempore. Saepe voluptate numquam
    et blanditiis et. Aspernatur nihil quasi qui amet aut aut. Temporibus rerum adipisci
    in odio necessitatibus sapiente.
- &11 !ruby/object:Author
  name: Alyse Baumbach
  biography: A enim voluptatem sequi qui dolores excepturi et molestiae. Qui tenetur
    repellendus dolor velit adipisci. Facere sint aut dolorum illo. Sit laudantium
    reprehenderit dolorum suscipit sed.
- &16 !ruby/object:Author
  name: Leonia Baumbach
  biography: Adipisci ipsum facere accusantium deserunt et iure ut illum. Sit impedit
    id mollitia quos tenetur nam natus. Reprehenderit consequatur amet quidem totam.
- &7 !ruby/object:Author
  name: Quinn Upton
  biography: Et commodi possimus cumque voluptatem excepturi accusamus. Libero voluptatem
    reiciendis harum quaerat. Saepe exercitationem dicta sunt pariatur fuga aspernatur.
    Sed explicabo consequatur hic excepturi minus.
- !ruby/object:Author
  name: Herbert Sporer
  biography: Excepturi cumque aut nihil quis similique dignissimos qui. Alias pariatur
    qui architecto doloremque voluptatem quasi. Voluptas est molestias perspiciatis
    qui.
- !ruby/object:Author
  name: Andrew Swift
  biography: Doloribus error omnis temporibus ipsam non quasi. Dolorum natus est eum
    dignissimos. Quaerat odit est enim aliquam consequatur.
- &13 !ruby/object:Author
  name: Lane Harber
  biography: Debitis molestiae repellat rerum voluptates modi molestiae possimus qui.
    Fuga nesciunt ullam debitis tempora sint sit. Reprehenderit aut qui molestiae
    minima ipsa ut eveniet eum.
- !ruby/object:Author
  name: Ericka Heathcote
  biography: Eveniet sapiente voluptas perspiciatis explicabo. Ab quaerat et odit
    quia sit et voluptate ducimus. Quidem in et nemo cupiditate voluptatem sunt doloribus.
    Et omnis nihil aut et unde aspernatur ut.
- !ruby/object:Author
  name: Kira Champlin
  biography: Aspernatur veniam eum explicabo dolores et ut itaque. Aut non adipisci
    ratione aut voluptatibus itaque dolore. Dolores autem nostrum magni et odio unde
    laudantium. Culpa quia excepturi doloribus mollitia.
- &4 !ruby/object:Author
  name: Maribeth Ziemann
  biography: Amet non quis consequatur assumenda ea eos cupiditate officiis. Maxime
    reiciendis ipsum fuga aut aut veritatis nihil. Quia sit in rerum eum.
- &1 !ruby/object:Author
  name: Kati Shanahan
  biography: Architecto modi distinctio iste ipsum et. Qui repellendus voluptas expedita
    ea porro eum. Est labore occaecati minus voluptates ut consequatur quibusdam.
    Ea non aliquid occaecati atque facere odit similique. Officiis nam incidunt qui
    neque quod ut quis qui.
- !ruby/object:Author
  name: Eleonore Powlowski
  biography: Blanditiis quam iste non quas. Quibusdam atque expedita quam et dolorum
    ratione. Molestiae sit aut est harum optio. Quos sapiente quo sit sed qui distinctio.
    Ut architecto doloribus nobis mollitia consectetur incidunt.
- !ruby/object:Author
  name: Laverna Spinka
  biography: Eum odio earum aspernatur dolores id aut voluptas. Et at totam expedita
    et modi provident non officia. Harum rerum minima dolor quaerat nobis modi soluta.
    Sunt et nisi in id ea.
- !ruby/object:Author
  name: Merri Willms
  biography: Laudantium architecto non quisquam deleniti. Aut temporibus autem qui
    et. Voluptas labore odit ut hic dignissimos et. Qui cumque dolore laboriosam officiis
    blanditiis est.
- &9 !ruby/object:Author
  name: Lacresha Kemmer
  biography: Rerum enim cupiditate modi veniam nulla. Sit similique ea aut quidem
    assumenda inventore. Odio eveniet unde natus est rerum vero ad. Necessitatibus
    quam expedita quo ratione quia inventore. Eum quis labore reiciendis neque animi.
- &17 !ruby/object:Author
  name: Dorothea Klocko
  biography: Ea nobis similique quasi minus id ipsum et. Provident totam expedita
    et quos voluptate minima suscipit quidem. Adipisci est dolorem nihil neque perferendis
    possimus iure.
- &8 !ruby/object:Author
  name: Leonida Nader
  biography: Deleniti culpa voluptatem accusantium veniam voluptatem atque. Enim architecto
    qui delectus accusantium veniam dolorum. Nesciunt officia id consequuntur et aliquid.
- &10 !ruby/object:Author
  name: Trudie Lockman
  biography: Modi eveniet quisquam et id ab. Soluta quaerat quisquam nulla ab ad repellendus.
    Corrupti aut explicabo eligendi sint.
- &12 !ruby/object:Author
  name: Robbie Durgan
  biography: Rerum adipisci placeat aut totam et necessitatibus ullam quis. Omnis
    quam aut quo eligendi. Repudiandae ut cumque quia vitae suscipit at rem dignissimos.
    Aut quia velit recusandae adipisci.
- &6 !ruby/object:Author
  name: Carmine Quigley
  biography: Et et id repellat maxime. Numquam accusantium assumenda eveniet temporibus
    fuga. Facere vel deserunt debitis possimus vitae quia. Est et molestiae enim quos
    nobis aspernatur consequuntur.
- &2 !ruby/object:Author
  name: Mitsuko Sanford
  biography: Voluptatum sapiente et sit velit dolor et. Necessitatibus est cum sapiente
    laborum exercitationem aliquam. Reiciendis vel aperiam laborum accusamus nemo
    et. Maxime nihil et est dolores.
:books:
- &50 !ruby/object:Book
  title: Case of the Missing Death Identity
  author: *1
- &41 !ruby/object:Book
  title: Journey of the Nuclear Clash
  author: *2
- &22 !ruby/object:Book
  title: Rise of the Killer City
  author: *3
- !ruby/object:Book
  title: The Nuclear Tentacle
  author: *4
- &59 !ruby/object:Book
  title: Planet of the Forbidden Rain
  author: *5
- &34 !ruby/object:Book
  title: Curse of the Flying Brain
  author: *6
- &57 !ruby/object:Book
  title: Tokyo Brain
  author: *7
- &30 !ruby/object:Book
  title: Curse of the Killer Identity
  author: *8
- &47 !ruby/object:Book
  title: Journey of the Death Diaries
  author: *9
- &20 !ruby/object:Book
  title: I Married a Flying City
  author: *10
- &28 !ruby/object:Book
  title: Red Monster
  author: *11
- !ruby/object:Book
  title: Tokyo Men
  author: *10
- &38 !ruby/object:Book
  title: Legend of Champagne Tears
  author: *6
- &54 !ruby/object:Book
  title: Journey of the Champagne Wizard
  author: *12
- !ruby/object:Book
  title: Flying Ninjas
  author: *8
- &51 !ruby/object:Book
  title: A Fistful of Champagne Ninja
  author: *10
- &39 !ruby/object:Book
  title: Action Wizard
  author: *13
- &18 !ruby/object:Book
  title: Curse of the Death Dreams
  author: *14
- &53 !ruby/object:Book
  title: Action Fly
  author: *15
- &24 !ruby/object:Book
  title: Day of the Green Hills
  author: *7
- &32 !ruby/object:Book
  title: Tokyo Wolves
  author: *4
- !ruby/object:Book
  title: Invasion of the American Men
  author: *4
- &43 !ruby/object:Book
  title: Forbidden Demon
  author: *8
- &35 !ruby/object:Book
  title: Blue Brains
  author: *16
- &49 !ruby/object:Book
  title: Fake Dreams
  author: *17
:readers:
- &60 !ruby/object:Reader
  name: Fanny McKenzie
  email: ammie@legrosondricka.ca
  city: Carterport
  street: Guadalupe Squares
  house: 62398
- &37 !ruby/object:Reader
  name: Julie Satterfield
  email: diedra.carroll@sipes.biz
  city: South Myrtice
  street: Runte Causeway
  house: 3850
- &48 !ruby/object:Reader
  name: Catherine Littel
  email: andrew@herzog.co.uk
  city: Port Dale
  street: Schowalter Common
  house: 92178
- &46 !ruby/object:Reader
  name: Karissa Eichmann
  email: chi_harber@boehmfritsch.co.uk
  city: Gleichnerstad
  street: Rozella Crossroad
  house: 276
- &52 !ruby/object:Reader
  name: Lenita Huel
  email: joey_watsica@zieme.info
  city: Daughertytown
  street: Goodwin Rest
  house: 30593
- &58 !ruby/object:Reader
  name: Marcie Kunde
  email: pamila@klocko.us
  city: Parkerton
  street: Johnny Estate
  house: 8359
- &45 !ruby/object:Reader
  name: Tangela Oga
  email: cliff@schuppepaucek.ca
  city: Wehnerhaven
  street: Zemlak Club
  house: 83492
- !ruby/object:Reader
  name: Elmer Bauch
  email: maryanna@strosinlockman.ca
  city: Cronintown
  street: Bergnaum Roads
  house: 481
- &25 !ruby/object:Reader
  name: Ward Stroman
  email: yong_kozey@lindbayer.name
  city: New Rosalia
  street: Rempel Wall
  house: 733
- &27 !ruby/object:Reader
  name: Magali Gislason
  email: ninfa_willms@sauer.ca
  city: West Wendyside
  street: Annie Road
  house: 30924
- &55 !ruby/object:Reader
  name: Susan Ankunding
  email: cecilia@robel.info
  city: Robertsview
  street: Myrna Viaduct
  house: 73025
- &33 !ruby/object:Reader
  name: Suzy Abernathy
  email: mathilde@mckenzie.co.uk
  city: Teresialand
  street: Sergio Parkway
  house: 809
- &29 !ruby/object:Reader
  name: Taina Hodkiewicz
  email: thao.wisoky@roberts.name
  city: North Brittenymouth
  street: Ron Falls
  house: 172
- &21 !ruby/object:Reader
  name: Blair Hodkiewicz
  email: kathie@sauer.ca
  city: Lake Billieville
  street: Isabell Overpass
  house: 98868
- &23 !ruby/object:Reader
  name: Lyla Christiansen
  email: bryon.swift@rosenbaum.biz
  city: Mitchellburgh
  street: Shaunta Summit
  house: 31479
- &31 !ruby/object:Reader
  name: Marco Douglas
  email: sol.lockman@gottlieb.com
  city: Port Paz
  street: Gerlach Cliffs
  house: 6789
- &36 !ruby/object:Reader
  name: Johanne Bernier
  email: callie@corwin.info
  city: West Andersonville
  street: Balistreri Land
  house: 81934
- &26 !ruby/object:Reader
  name: Kasie Corkery
  email: laci_konopelski@monahan.info
  city: Catherynborough
  street: Douglas Ramp
  house: 928
- &19 !ruby/object:Reader
  name: Zonia Kutch
  email: babette@heidenreichcassin.name
  city: Ricefort
  street: Kreiger Alley
  house: 37259
- &42 !ruby/object:Reader
  name: Kathleen Glover
  email: verdell.ritchie@smith.co.uk
  city: Kutchmouth
  street: Farrell Crossing
  house: 86303
- !ruby/object:Reader
  name: Hank Rippin
  email: tiara@spinka.biz
  city: Lake Valarie
  street: Leuschke Branch
  house: 2128
- !ruby/object:Reader
  name: Meggan Kessler
  email: lamont_predovic@kozey.com
  city: Karrenshire
  street: Bernhard Canyon
  house: 428
- &44 !ruby/object:Reader
  name: Norah Schroeder
  email: cody@west.ca
  city: Port Shenaland
  street: Bosco Harbors
  house: 3563
- &56 !ruby/object:Reader
  name: Josephine Orn
  email: briana@treutelabernathy.co.uk
  city: East Bevville
  street: Charlena Club
  house: 63615
- &40 !ruby/object:Reader
  name: Leighann Abshire
  email: makeda.dubuque@block.co.uk
  city: Port Brianatown
  street: Joya Parkway
  house: 407
:orders:
- !ruby/object:Order
  book: *18
  reader: *19
  date: 2019-07-23
- !ruby/object:Order
  book: *20
  reader: *21
  date: 2019-07-23
- !ruby/object:Order
  book: *22
  reader: *23
  date: 2019-07-23
- !ruby/object:Order
  book: *24
  reader: *25
  date: 2019-07-23
- !ruby/object:Order
  book: *20
  reader: *26
  date: 2019-07-23
- !ruby/object:Order
  book: *18
  reader: *27
  date: 2019-07-23
- !ruby/object:Order
  book: *28
  reader: *29
  date: 2019-07-23
- !ruby/object:Order
  book: *30
  reader: *31
  date: 2019-07-23
- !ruby/object:Order
  book: *32
  reader: *33
  date: 2019-07-23
- !ruby/object:Order
  book: *34
  reader: *29
  date: 2019-07-23
- !ruby/object:Order
  book: *35
  reader: *36
  date: 2019-07-23
- !ruby/object:Order
  book: *30
  reader: *27
  date: 2019-07-23
- !ruby/object:Order
  book: *18
  reader: *37
  date: 2019-07-23
- !ruby/object:Order
  book: *38
  reader: *33
  date: 2019-07-23
- !ruby/object:Order
  book: *39
  reader: *40
  date: 2019-07-23
- !ruby/object:Order
  book: *38
  reader: *33
  date: 2019-07-23
- !ruby/object:Order
  book: *41
  reader: *40
  date: 2019-07-23
- !ruby/object:Order
  book: *20
  reader: *42
  date: 2019-07-23
- !ruby/object:Order
  book: *43
  reader: *44
  date: 2019-07-23
- !ruby/object:Order
  book: *41
  reader: *45
  date: 2019-07-23
- !ruby/object:Order
  book: *43
  reader: *45
  date: 2019-07-23
- !ruby/object:Order
  book: *24
  reader: *46
  date: 2019-07-23
- !ruby/object:Order
  book: *47
  reader: *44
  date: 2019-07-23
- !ruby/object:Order
  book: *18
  reader: *26
  date: 2019-07-23
- !ruby/object:Order
  book: *30
  reader: *48
  date: 2019-07-23
- !ruby/object:Order
  book: *49
  reader: *29
  date: 2019-07-23
- !ruby/object:Order
  book: *50
  reader: *42
  date: 2019-07-23
- !ruby/object:Order
  book: *47
  reader: *37
  date: 2019-07-23
- !ruby/object:Order
  book: *51
  reader: *52
  date: 2019-07-23
- !ruby/object:Order
  book: *53
  reader: *25
  date: 2019-07-23
- !ruby/object:Order
  book: *47
  reader: *42
  date: 2019-07-23
- !ruby/object:Order
  book: *49
  reader: *25
  date: 2019-07-23
- !ruby/object:Order
  book: *47
  reader: *21
  date: 2019-07-23
- !ruby/object:Order
  book: *49
  reader: *37
  date: 2019-07-23
- !ruby/object:Order
  book: *54
  reader: *42
  date: 2019-07-23
- !ruby/object:Order
  book: *22
  reader: *55
  date: 2019-07-23
- !ruby/object:Order
  book: *28
  reader: *56
  date: 2019-07-23
- !ruby/object:Order
  book: *57
  reader: *25
  date: 2019-07-23
- !ruby/object:Order
  book: *57
  reader: *44
  date: 2019-07-23
- !ruby/object:Order
  book: *54
  reader: *58
  date: 2019-07-23
- !ruby/object:Order
  book: *59
  reader: *27
  date: 2019-07-23
- !ruby/object:Order
  book: *39
  reader: *44
  date: 2019-07-23
- !ruby/object:Order
  book: *39
  reader: *52
  date: 2019-07-23
- !ruby/object:Order
  book: *51
  reader: *60
  date: 2019-07-23
- !ruby/object:Order
  book: *22
  reader: *19
  date: 2019-07-23
- !ruby/object:Order
  book: *41
  reader: *55
  date: 2019-07-23
- !ruby/object:Order
  book: *50
  reader: *25
  date: 2019-07-23
- !ruby/object:Order
  book: *59
  reader: *21
  date: 2019-07-23
- !ruby/object:Order
  book: *51
  reader: *46
  date: 2019-07-23
- !ruby/object:Order
  book: *18
  reader: *27
  date: 2019-07-23
